[package]
name = "pyseph/objectcache"
version = "1.4.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A robust, blazing fast model and part cache for Roblox."
license = "MIT"